services:
  db:
    image: mysql
    container_name: smart-system-api-db
    restart: always
    tty: true
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: projectdb
