# Use a Node.js base image
FROM node:22-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and yarn.lock
COPY package.json .

# Install dependencies
RUN yarn install

# Copy the rest of your application
COPY . .

# Install Prisma globally
RUN yarn global add prisma

# Expose port
EXPOSE 3000

# Command to run the application
CMD ["yarn", "start"]
